require_relative 'ruloz/logic_value'
require_relative 'ruloz/pin'
require_relative 'ruloz/connection'
require_relative 'ruloz/component'
require_relative 'ruloz/system'
require_relative 'ruloz/vcd_generator'
